bn:
    languageName: "Bangla"
    languageAltTitle: Bengali
    weight: 2
    #title: Unplugging From The Matrix
    profileMode:
        enabled: false
en:
    languageName: "English"
    weight: 1
    #title: Unplugging From The Matrix
    profileMode:
        enabled: false
