baseURL = 'https://abdibbo.github.io/'
languageCode = 'en-us'
title = 'Unplugging From The Matrix'
theme = "m10c"


[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/vaga"
  
  [params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#ffffff"
